### ISSUE TITLE
[New Feature]: Increase "verbosity" option for tracking progress.

### ISSUE THREAD

**Issue by coforfe** [suiji/Arborist#13]
It would be interesting to include in `RBorist` a functionality that package `ranger` has already implemented.

`ranger` package has a nice feature that although it is purely informative, it helps monitor the progress during the model execution.

The output of a `ranger` model with this **verbosity** activated is like this:

``` r
> datIn  <- twoClassSim(n = 50000)
> modFit <- ranger( Class ~., data= datIn, num.trees = 1000, mtry = 4, verbose = TRUE)
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 19 seconds.
```

Thanks,
Carlos.

**Comment by suiji** [comment]
The development branch now has the hooks to report diagnostics back to the user.  Although these were introduced to report the state of coprocessor involvement, the underlying mechanism should be versatile enough to support **verbose** observations.  IOW, we should see something in the next release.

**Comment by suiji** [comment]
Initial support for **verbose** has been introduced.  Progress is announced as each major phase is completed.  The option will become a bit more informative when training is performed in batches, rather than _en banc_.
