### ISSUE TITLE
Feature request: Include OOB error as an attribute of the 'validation' object

### ISSUE THREAD

**Issue by talgalili** [suiji/Arborist#19]
Is it possible to get the out of bag error of the model? I can't seem to find this in the object or any function that gets it.

(if not - then I think this is an important feature to include)

**Comment by suiji** [comment]
Right now it would have to be computed from the residuals.  We can easily include it as an attribute of the 'validation' object, in future.

**Comment by talgalili** [comment]
That would be very helpful, thanks.

**Comment by suiji** [comment]
Just now getting to this - there were squeakier wheels to oil.

For classification, we will report OOB error as the mean misprediction rate.

For regression, we already report MSE and R-squared.  Would you like to see a mean error rate, as well?

**Comment by talgalili** [comment]
I think the MSE is probably fine, although it never hearts to add another error measure.

**Comment by suiji** [comment]
Not a problem.  Should be available soon.

**Comment by suiji** [comment]
Validation now includes oob error, as discussed.  Regression now reports mean absolute error.

Please feel free to re-open this item if other issues arise.
