### ISSUE TITLE
Predict() give different values on original data

### ISSUE THREAD

**Issue by ebee20070101** [suiji/Arborist#20]
Hi, 
I used the example in predict() in the Rborist manual,
rb <- Rborist( x, y )
predX <- predict( rb, x )

But predX$yPred is very different from
rb$validation$yPred

Is this expected?
Original randomForest package gave identical predicted value vector on same operation.

**Comment by suiji** [comment]
In general, they would be expected to differ:

For each row, the "predict" method aggregates the predictions yielded by every tree.  The "validate" method, however, aggregates only predictions yielded by those tees for which the given row is not bagged.
