### ISSUE TITLE
daugherL

### ISSUE THREAD

**Issue by sorhawell** [suiji/Arborist#4]
Tiny stuff. Variable "daughterL" is named "daugherL" in [[rcppEcport.cc](https://github.com/suiji/Arborist/blob/d3857b1a27d86d56d35c9c026ca5cc220ef92b63/ArboristBridgeR/Shared/rcppExport.cc)] line 248
```
List ffTree = List::create(
     _["pred"] = pred[tIdx],
     _["daugherL"] = incrL,
     _["daughterR"] = ifelse(incrL == 0, 0, incrL + 1),
     _["split"] = split[tIdx],
     _["facSplit"] = facSplit[tIdx],
     _["bag"] = bag[tIdx]
     );
```

**Comment by suiji** [comment]
Fixed.
Thank you for the report.
