### ISSUE TITLE
Statement on code availability in README.md

### ISSUE THREAD

**Issue by mnwright** [suiji/Arborist#47]
Mark, great to see that you continue working on the Arborist. 

In the [README.md](https://github.com/suiji/Arborist#performance) you write in the performance section:

> This paper compares several implementations of the Random Forest algorithm, including the Arborist: (https://www.jstatsoft.org/article/view/v077i01/v77i01.pdf). The paper does not include the code on which timings were benchmarked, however, despite the journal's claim to promote reproducible research. As the Arborist has undergone several updates since the paper was written, then, there is unfortunately no way to gauge whether the authors' original findings remain relevant.

The code is included. See https://www.jstatsoft.org/article/view/v077i01.

**Comment by suiji** [comment]
Thank, Marvin.  Please accept my apologies for missing the reference.  The URL now appears in the READM#.
